name: .NET Core push on feature branch

on:
  push:
    branches: [feature/*]

env:
  PROJECT_NAME: FweetMicroservice

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build
        run: dotnet build
      
      # Test the project
      - name: Test
        run: dotnet test

  sonarscanner:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          testCommand: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          projectKey: S6FwutterFontys_${{ env.PROJECT_NAME }}
          projectName: ${{ env.PROJECT_NAME }}
          sonarOrganisation: s6fwutterfontys
          beginArguments: >
              /d:sonar.verbose="true"
              /d:sonar.cs.opencover.reportsPaths='"./${{ env.PROJECT_NAME }}Tests/coverage.xml"'
              /d:sonar.coverage.exclusions='"**/*.cs","**/*.md","**/sonar-project.properties"'
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}